### ISSUE TITLE
Issues when installing github integration and opening PR on a project with Peril

### ISSUE THREAD

**Issue by MaximeHeckel** [danger/peril#11]
I've Peril all set up, followed each *new* steps of the read me (cf #10) but I got the following issues:

When installing the plugin on one of my repo I'm getting:
```
Error:  [Error: error:0906D066:PEM routines:PEM_read_bio:bad end line]
```
I guess that's because I don't have a bio maybe?

Second issue is perhaps mongo related, whenever I open a PR I'm getting from peril:

```
Error:  [TypeError: Cannot read property 'findOne' of undefined]
```

From the `mongo.ts` file I've deducted that maybe I had an issue getting my db and collection in mongo. However everything seems in order:

```
> show dbs
github_installations  0.078GB
local                 0.078GB
> use github_installations
switched to db github_installations
> show collections
github_integrations
system.indexes
```

**Comment by orta** [comment]
> Error:  [Error: error:0906D066:PEM routines:PEM_read_bio:bad end line]
 
Sounds like it's having problems signing with your certificate in the `default.json` I'd double check that, Peril needs these to create access tokens to do any networking.

This is all still in pre-production, ( I'm not using it anywhere because it needs to be 100% secure as all our projects are OSS ) so I'd recommend having a dig around and seeing what's up :)

**Comment by MaximeHeckel** [comment]
I'll take a look and give updates on this.
Thanks!

**Comment by MaximeHeckel** [comment]
The first issue was indeed a wrong certificate (Note in your `default.sample.json` you miss the last line of the certificate)
#13 should fix the second issue related to mongo (at least it allowed me to go a bit further)

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
Oops, I should provide a better example there

**Comment by MaximeHeckel** [comment]
Closing this since all the issues mentioned have been fixed
