### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by orta** [danger/peril#138]
I'd like a scheduler - this would execute a Dangerfile with an instance of the github API at a scheduled rate and do specific jobs, here's a few tasks that I'd do with this:

* Ensure all github repos have their labels in sync - https://github.com/artsy/artsy-danger/issues/10
* Ensure all github repos have a README that pass - https://github.com/orta/artsy-check-readmes

**Comment by flovilmart** [comment]
scheduling is hard :P how do you envision it? a setTimeout in the process, a cron on a standalone danger like `danger --sanity --source path/to/Dangerfile.js` ?

**Comment by orta** [comment]
I'm also a bit unsure, maybe a heroku scheduler would keep things neatly separated in terms of abstraction. I've used setTimeout a bunch and also not really had a problem with it, so don't really have opinions 🍡 :D

**Comment by flovilmart** [comment]
from what I see with parse-server, a standalone batch executor (that is side-effect-less) is better.

**Comment by orta** [comment]
Thanks!

**Comment by orta** [comment]
OK, we now have all sorts of scheduling options (in x amount of minutes, every x minutes) 

https://github.com/danger/peril/blob/master/docs/settings_repo_info.md#scheduler
