### ISSUE TITLE
Docker Instructions

### ISSUE THREAD

**Issue by nsfmc** [danger/peril#148]
I have peril currently working locally running on my machine in docker as part of setting it up to work on a t2nano i provisioned a while ago for work. i didn't use compose because it seemed a bit much for this purpose, but i could be convinced otherwise.

the dockerfile is actually pretty straightforward, i used alpine node but it can be whatever, as long as git gets installed somehow.
```docker
FROM node:8.4.0-alpine 
WORKDIR /opt

RUN apk add --no-cache git

ENV PERIL_HASH 62e1d5e6f77f1a99601b197e3eb62172d9c43b2f

RUN git clone https://github.com/danger/peril.git peril
WORKDIR peril
RUN git checkout $PERIL_HASH

# ignore for now since our 8 !== 7 (requested)
RUN yarn --ignore-engines

# server lives on 5000
EXPOSE 5000

CMD ["node", "out/index.js"]
```

once this is built and pulled into my aws instance, i have a convenience script to start peril

```shell
export DATABASE_JSON_FILE="studiosnack/peril-config@peril-settings.json"

function is_container() {
    local CONTAINER=$1
    RUNNING=$(docker inspect --format="{{ .State.Running }}" $CONTAINER 2> /dev/null)
    if [ $? -eq 1 ]; then
        echo false
        return
    fi

    echo true
}

function remove_container() {
    local CONTAINER=$1
    if $(is_container $CONTAINER); then
        echo "Removing container $CONTAINER"
        docker rm -f $CONTAINER
        echo "Removed container $CONTAINER"
    else
        echo "Container $CONTAINER not running"
    fi
}

function remove_if_running() {
    local CONTAINER=$1
    if $(is_container $CONTAINER); then
        remove_container $CONTAINER
    fi
}

remove_if_running local-peril

docker run --name local-peril \
  -e PRIVATE_GITHUB_SIGNING_KEY \
  -e PERIL_INTEGRATION_ID \
  -e PERIL_ORG_INSTALLATION_ID \
  -e PERIL_WEBHOOK_SECRET \
  -e DATABASE_JSON_FILE \
  -d -it -p 8181:5000 studiosnack/peril

docker exec local-peril yarn setup
```

this is missing a host of env vars, as you can see. in AWS and locally, i solve this problem with aws [parameter store](https://aws.amazon.com/ec2/systems-manager/parameter-store/) and [chamber](https://github.com/segmentio/chamber) and invoke it like so.

`chamber exec peril -- ./run.sh`

but without that, you can also seed the appropriate env vars into the shell and run the script (a previous version of that shell script did something like)
```shell
export PERIL_INTEGRATION_ID="23"
export PERIL_ORG_INSTALLATION_ID="23"
# not used right now (not sure if we should)
export PERIL_BOT_USER_ID="23"
export PERIL_WEBHOOK_SECRET="secretsecretsarenofun"
export PRIVATE_GITHUB_SIGNING_KEY=$(cat ./github_signing_key.pem)
```

from running this, i am able to commit changes to the peril config repo and see those changes propagate during subsequent commits/prs, but i'm wondering if there is some detail (like setup) that needs to happen with a full set of env vars at build time (or similar) so that the env is ready to go.

i'm not sure if you had some other idea for how docker should be set up, since peril no longer has a hard postgres requirement and is capable of updating its ruleset definitions, it seems like the docker config isn't super onerous, but i might be missing something.

let me know if you have any feedback and i can turn this into a pr or documentation file

**Comment by orta** [comment]
Yeah, there is only ENV settings that _have_ to be set at the initial compile time is `DATABASE_JSON_FILE` but you are handling it by running `yarn setup` manually. Which should be fine. 

I don't know too much about docker, but the whole thing looks 👍  to me.

**Comment by nsfmc** [comment]
closing this btw, but if you think some general guidance would be useful, i'd be happy to extract this into a pr for the docs
