### ISSUE TITLE
Investigate into a fully separated peril system, by using AWS Lambda for a Danger run

### ISSUE THREAD

**Issue by orta** [danger/peril#159]
I once had a great chat with @bkeepers once about Lamba as a option for user security, today this really clicked into place as to how this could work with Peril. 

In Danger JS, there is a tool called `danger process` - http://danger.systems/js/usage/danger-process - by separating the danger setup, vs the danger run then it allows any language to create their own runtime without all the faffing.

By the same process, Peril can do all the setup, and lambda can handle running the dangerfile. This could handle my two biggest problems: Handling running a lot of dangerfiles and the security issues around running a Dangerfile safely.

In this setup:

* GitHub sends events to Peril
* Peril decides what to run
* For everything that needs to run, Peril will download and set up a lambda "job"  (I don't know the terminology) 
* The lambda job receives a post with the DSL, and an access token (and anything else that is critical)

Questions for me to figure:

- [x] What is a lambda job?  🥇 
- [x] Can I provide node modules in some customizable way?  ( I probably don't need to for the main Peril though )
- [x] This feels like a pretty scalable approach 👍 - is it?

**Comment by orta** [comment]
I ran through the [serverless](http://serverless.com) tutorial, and then took a look at how AWS lambdas work. The idea seems to fit, there's a limit to data sent to a job at 6MB, which I think we can keep the DSL under. 

 https//hd6geu40s4.execute-api.us-east-1.amazonaws.com/dev/api/danger/run

**Comment by orta** [comment]
Bit worried about the re-use though: https://aws.amazon.com/blogs/compute/container-reuse-in-lambda/

**Comment by orta** [comment]
Though I could do this:

> There’s also effectively a fourth way to exit – by crashing or calling `process.exit()`. For example, if you include a binary library with a bug and it segfaults, you’ll effectively terminate execution of that container.

**Comment by orta** [comment]
I spent a bit more time thinking out loud about this with @craigspaeth

I'd like the role of the "peril" server here to be about setup and execution of jobs, so perhaps it makes sense to move more of the logic into AWS. Here's how it could work.

* A webook from GitHub goes to Peril
* Peril then looks up the org internally, figures all their settings, then decides if anything needs to happen
* If something should happen, Peril sends off a lambda job posting something similar to  [GitHubRunSettings](https://github.com/danger/peril/blob/0a6b2a5cb38e9917b6c244896e46c96f5d41fa6e/source/github/events/github_runner.ts#L40-L51)
* The job generates the DSL
* _Maybe_ there could be a second job, or maybe it can be in the first job will then execute the JS Dangerfiles.

This is blocked by https://github.com/danger/danger-js/pull/395 which provides a lot of tooling/typing inside danger for handling process separated JS.

**Comment by orta** [comment]
TBH, https://hyper.sh looks like a better option then AWS lambda

**Comment by orta** [comment]
WIP happening, it's got merged and is building on https://hub.docker.com/r/dangersystems/peril/

**Comment by orta** [comment]
This has been working for 2 months on the danger org, I’ve started looking at moving this infra to be on a staging env

**Comment by SD10** [comment]
Hey @orta, I got a little bit lost in this thread. Is the reasoning behind this for security concerns of executing the dangerfile? Essentially, you're allowing users to run the dangerfile in their own environment?

What I'm looking into is using peril to trigger some heavier work to be done on a remote machine where I need to download resources from multiple repositories

**Comment by orta** [comment]
This is now done and sorted.
