### ISSUE TITLE
Permissions for Peril integration

### ISSUE THREAD

**Issue by MaximeHeckel** [danger/peril#18]
I'm getting 401 whenever I open/close a Pull Request with Peril/DangerJS and I wondered if my integration is set correctly, I keep comparing with the Danger one, but I can't see what I've missed

![integrations_-_peril](https://cloud.githubusercontent.com/assets/2974412/22476974/339a1856-e799-11e6-8fce-aa0116bf8ee8.png)
![integrations_-_peril](https://cloud.githubusercontent.com/assets/2974412/22476982/3c50d1ec-e799-11e6-9360-1743e397831f.png)

**Comment by orta** [comment]
This is my current setup:

![screen shot 2017-01-31 at 12 41 23 pm](https://cloud.githubusercontent.com/assets/49038/22477051/9a6141d6-e7b2-11e6-9bae-91ea033af4d0.png)

![screen shot 2017-01-31 at 12 41 26 pm](https://cloud.githubusercontent.com/assets/49038/22477052/9b9c8998-e7b2-11e6-9f4b-61bd8222b043.png)

**Comment by orta** [comment]
Where are you seeing the 401?

**Comment by MaximeHeckel** [comment]
I'm getting
```
peril_1    | Request failed: {
peril_1    |   "url": "https://api.github.com/repos/MaximeHeckel/website/pulls/18",
peril_1    |   "status": 401,
peril_1    |   "statusText": "Unauthorized",
....
```

So whenever Danger tries to get some data from the PR I guess

**Comment by orta** [comment]
I feel like I had something in here to allow curling every request Danger/Peril makes - is that available for you to see what's up with the auth token?

**Comment by orta** [comment]
( I started getting my peril set back up https://github.com/danger/danger-js/pull/136  - I'm expecting to having it running again on my computer by the end of the day, got a few more upcoming meetings )

**Comment by MaximeHeckel** [comment]
```
 is that available for you to see what's up with the auth token?
```
What exactly do you mean by that?

**Comment by orta** [comment]
So the general process is that Peril will use the pem to generate a temporary auth token just for that repo, that peril-specific auth key is passed into Danger's GitHub object and then Danger runs. 

So there must be an API call to grab a token, then that token should be valid for the specific repo

**Comment by orta** [comment]
So I think you can replicate the API requests peril takes in the CLI to see where the disconnect happens

**Comment by MaximeHeckel** [comment]
Ok I will investigate that

**Comment by MaximeHeckel** [comment]
What I found out is that Danger doesn't seem to be able to get my token
```
peril_1    | https://api.github.com/repos/MaximeHeckel/website/pulls/20
peril_1    | { method: 'GET',
peril_1    |   body: {},
peril_1    |   headers:
peril_1    |    { Authorization: 'token null',
peril_1    |      'Content-Type': 'application/json' } }
```
Reading through the code, it should get it from the `DANGER_GITHUB_API_TOKEN` envvar right? (I currently have it on my env)

**Comment by orta** [comment]
No, this token should be generated by [Peril's integration](https://github.com/danger/peril/blob/master/source/api/github.ts#L8-L27) then passed into Danger [here](https://github.com/danger/peril/blob/master/source/danger/danger_runner.ts#L35)

**Comment by orta** [comment]
Somehow your  `integration.accessToken,` is null after it requests a new one

**Comment by MaximeHeckel** [comment]
Ok I checked mongo and indeed the entry had no access token,
Reinstalling the integration fixed it
Thank you so much for your help! 👍

**Comment by orta** [comment]
Thanks to you for taking the brunt of being the 1st other user ;)

**Comment by MaximeHeckel** [comment]
Actually now I think I'm having permission issues
Danger seems to work fine, and is making most calls to Github without a problem
However, after a while I'm getting:

```
peril_1    | Request failed: {
peril_1    |   "url": "https://api.github.com/user",
peril_1    |   "status": 403,
peril_1    |   "statusText": "Forbidden",

peril_1    | Error:  Error: 403
peril_1    |     at /node_modules/danger/distribution/api/fetch.js:49:19
peril_1    |     at process._tickCallback (internal/process/next_tick.js:103:7)
...
```

The request seems legit compared to the others, it's using the same token.

(Note: The repository where the integration is installed is private)

**Comment by orta** [comment]
Tokens are short-lived, could it not be successfully re-creating them?

**Comment by MaximeHeckel** [comment]
That token is apparently still valid (I got this issue right after successfully reinstalling the integration and getting all the data in the mongo DB)

**Comment by orta** [comment]
Does any requests work when you use the same headers?

**Comment by MaximeHeckel** [comment]
Yes other requests work just fine, I'm logging everything:
```
peril_1    | https://api.github.com/repos/MaximeHeckel/website/pulls/22
peril_1    | { method: 'GET',
peril_1    |   body: {},
peril_1    |   headers:
peril_1    |    { Authorization: 'token v1.43a0b4ade29ac3fc73bd9e182cb1c7dbd39115fd',
peril_1    |      'Content-Type': 'application/json' } }
peril_1    | https://api.github.com/repos/MaximeHeckel/website/contents/dangerfile.js?ref=staging
peril_1    | { method: 'GET',
peril_1    |   body: {},
peril_1    |   headers:
peril_1    |    { Authorization: 'token v1.43a0b4ade29ac3fc73bd9e182cb1c7dbd39115fd',
peril_1    |      'Content-Type': 'application/json' } }
peril_1    | https://api.github.com/repos/MaximeHeckel/website/pulls/22
peril_1    | { method: 'GET',
peril_1    |   body: {},
peril_1    |   headers:
peril_1    |    { Authorization: 'token v1.43a0b4ade29ac3fc73bd9e182cb1c7dbd39115fd',
peril_1    |      'Content-Type': 'application/json',
peril_1    |      accept: 'application/vnd.github.v3.diff' } }
peril_1    | https://api.github.com/repos/MaximeHeckel/website/pulls/22/commits
peril_1    | { method: 'GET',
peril_1    |   body: {},
peril_1    |   headers:
peril_1    |    { Authorization: 'token v1.43a0b4ade29ac3fc73bd9e182cb1c7dbd39115fd',
peril_1    |      'Content-Type': 'application/json' } }
peril_1    | https://api.github.com/repos/MaximeHeckel/website/pulls/22
peril_1    | { method: 'GET',
peril_1    |   body: {},
peril_1    |   headers:
peril_1    |    { Authorization: 'token v1.43a0b4ade29ac3fc73bd9e182cb1c7dbd39115fd',
peril_1    |      'Content-Type': 'application/json' } }
peril_1    | https://api.github.com/repos/MaximeHeckel/website/pulls/22/commits
peril_1    | { method: 'GET',
peril_1    |   body: {},
peril_1    |   headers:
peril_1    |    { Authorization: 'token v1.43a0b4ade29ac3fc73bd9e182cb1c7dbd39115fd',
peril_1    |      'Content-Type': 'application/json' } }
peril_1    | Found some validation failure
peril_1    | https://api.github.com/user
peril_1    | { method: 'GET',
peril_1    |   body: {},
peril_1    |   headers:
peril_1    |    { Authorization: 'token v1.43a0b4ade29ac3fc73bd9e182cb1c7dbd39115fd',
peril_1    |      'Content-Type': 'application/json' } }
peril_1    | Request failed: {
peril_1    |   "url": "https://api.github.com/user",
peril_1    |   "status": 403,
peril_1    |   "statusText": "Forbidden",
....
```

**Comment by orta** [comment]
Could that be something called from the Dangerfile?  I wonder if it's an API request that needs specifically looking at

I don't know if an integration _has_ a user account - so it's very possible that the 403 is correct

**Comment by orta** [comment]
The API call is allowed on the list - https://developer.github.com/early-access/integrations/available-endpoints/#Users

but if there's no associated user?

**Comment by orta** [comment]
try overwriting the github's `getUserID` with something like: ` github.getUserID = () => Promise.resolve(111_`

**Comment by MaximeHeckel** [comment]
<img width="859" alt="peril_by_maximeheckel_ _pull_request__26_ _maximeheckel_website" src="https://cloud.githubusercontent.com/assets/2974412/22495288/dabd3320-e7f3-11e6-9d76-d02148c7af78.png">

This made it work!!

**Comment by orta** [comment]
interesting, so I wonder if Peril knows how to recognise and amend the same issue without that faked networking request giving something useful

**Comment by MaximeHeckel** [comment]
So far I still haven't found a fix for this issue. I just added a diff file to fake that request.
What is (or would be, since it doesn't look like it's mandatory) the use of the userID to post on the PR? If I remember correctly it was (among) the last request(s).

**Comment by orta** [comment]
Danger in this case will look up her account to see if she has already posted a message, so that the message can be edited or deleted instead of posting a new one each time. As it fails, which that function can do, then Danger will safely consider that there are no posts already

**Comment by orta** [comment]
Alright - I'm going to close this, a lot of this discussion is now superseded by the getting started on my org docs 👍 https://github.com/danger/peril/blob/master/docs/setup_for_org.md
