### ISSUE TITLE
Anyway to include another dangerfile?

### ISSUE THREAD

**Issue by urkle** [danger/peril#200]
So I have a set of common rules for every repo in my org.   But some of the projects have specific checks that only apply to them.   Is there a way to include another dangerfile in so I can easily share code?

**Comment by orta** [comment]
Depends on how you do it:

* **via code** no, I need to hook into the `require` functions and start supporting async downloading via the GH API. I  [started this](https://github.com/danger/peril/tree/async_import) but it's tricky trying to keep track of your relative files.

* **via peril.settings.json**, sure 

```json
{
  "rules": {
    "pull_request": "artsy/artsy-danger@org/all-prs.ts",
    "pull_request.closed": "artsy/artsy-danger@org/closed-prs.ts"
  },
  "repos": {
    "artsy/reaction": {
      "pull_request": "danger/pr.ts"
    },
    "artsy/positron": {
      "pull_request": "dangerfile.ts"
    },
  }
```

will run two dangerfiles for a PR on `artsy/reaction` and `artsy/positron` but only one for `artsy/eigen`

**Comment by orta** [comment]
You can also run multiple dangerfiles from a single webhook now:

```
{
  "settings": {
    "modules": ["danger-plugin-spellcheck", "danger-plugin-yarn", "@slack/client", "semver-sort"]
  },
  "rules": {
    "create": "danger/peril-settings@org/new_tag.ts",
    "pull_request.closed": "danger/peril-settings@org/aeryn.ts",
    "pull_request": ["danger/peril-settings@org/debug.ts", "danger/peril-settings@org/changelog.ts"]
  }
}
```

But I'm still figuring out how to do local imports - likely going to be doing it by dynamic imports - https://github.com/tc39/proposal-dynamic-import

**Comment by orta** [comment]
This came in with https://github.com/danger/peril/pull/346
