### ISSUE TITLE
Potential problem with github.utils.fileContents

### ISSUE THREAD

**Issue by mxstbr** [danger/peril#245]
I tried adding my very own [`danger-plugin-flow`](https://github.com/withspectrum/danger-plugin-flow) to our Peril setup (https://github.com/withspectrum/peril-settings), but as soon as I did that and added an unflowtyped file (to make the plugin fail to see whether it works or not) I got a "Bad credentials" error:

<img width="735" alt="screen shot 2018-04-25 at 21 02 11" src="https://user-images.githubusercontent.com/7525670/39267841-593d5306-48ce-11e8-8408-8a90290d6b62.png">

Any clues what could be happening here? I specifically used `github.utils.fileContents` instead of `fs` for Peril compat, but I might totally be missing something.

**Comment by mxstbr** [comment]
That'd mean something's going wrong here, right? 

https://github.com/danger/danger-js/blob/3eb635cb61885187e39ec9c2cf35c32de2317779/source/runner/jsonToDSL.ts#L46-L62

**Comment by mxstbr** [comment]
Too many layers of indirection for an outside to follow 😅 Not sure where the problem could lie beyond that method, any ideas?

**Comment by orta** [comment]
Yeah, no, I woundn't recommend digging into this one! The heart of the danger runner is super complex I'm afraid

But it's something around this.

**Comment by orta** [comment]
I have a long flight tomorrow where I intend to work on #243 - so I'll keep my eyes open for this too

**Comment by mxstbr** [comment]
Sounds great to me, thank you!

**Comment by mxstbr** [comment]
Let me know when a new release is out—I'll have to deploy a fresh version of Peril for it to update, right?

**Comment by orta** [comment]
Yep, see https://github.com/danger/peril/blob/master/docs/updating_peril.md

**Comment by mxstbr** [comment]
IT WORKED!!! :tada:

<img width="786" alt="screen shot 2018-04-27 at 16 25 02" src="https://user-images.githubusercontent.com/7525670/39367606-8fe7e942-4a37-11e8-8d3e-e309b066cbf5.png">

Thanks for the quick resolution here, much appreciated.

**Comment by orta** [comment]
Thanks for the solid bug report, I should move some of my plugins to use that API too

**Comment by mxstbr** [comment]
Ah crap, I spoke too soon, now it's no longer editing its own comments:

<img width="785" alt="screen shot 2018-04-27 at 16 25 48" src="https://user-images.githubusercontent.com/7525670/39367640-b19b38e6-4a37-11e8-843d-17d558508372.png">

**Comment by mxstbr** [comment]
I definitely have all the env vars set correctly since this worked before as long as I wasn't using the GitHub API, so it's gotta be something in that same area of the code probably?

**Comment by orta** [comment]
Hrm, could it be  https://github.com/danger/peril/issues/219 ?

**Comment by orta** [comment]
However, the env var to double check is `PERIL_BOT_USER_ID`

**Comment by mxstbr** [comment]
Definitely sounds like #219

**Comment by orta** [comment]
OK, I'll have a proper think about this over the weekend. 

It should be possible to add support coalescing multiple runs to all happen sycnronously without a db, had a think about it on the airplane

**Comment by mxstbr** [comment]
Closing as a duplicate of #219 and tracking that!
