### ISSUE TITLE
Allow users to specify specific label names in labeled events

### ISSUE THREAD

**Issue by SD10** [danger/peril#259]
I want to perform an action when a specific label is added:
```json
"rules": {
   "issues.labeled.question": "Moya/moya-peril/@org/someTask.ts"
}
```

**Comment by orta** [comment]
I'm wary of this, because I'd have to start making all sorts of weird one-offs like this.

I think if you can think of a smart way to make a generic "if the JSON includes this keypath or value" encoded into the rule, I'd be game

**Comment by SD10** [comment]
Yeah, the latter is preferred. I have no intention of trying to push something hacky through. 
Could be a couple more weeks till I'm comfortable enough with TypeScript but I'll explore this 😊

**Comment by orta** [comment]
Cool beans, the code you want is here, https://github.com/danger/peril/blob/node/source/danger/danger_run.ts#L36

You'll need to make it also accept the full body JSON as well as event/action

**Comment by SD10** [comment]
Thanks, I was looking at that yesterday for #126 and I was confused by this line:
https://github.com/danger/peril/blob/c113cc58f88a889556e0e694ae424e36f2e8f748/source/db/index.ts#L107-L108
I was expecting it to be a `PerilEventString` but I'm not well acquainted with TypeScript interfaces

**Comment by orta** [comment]
This is in
