### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by steprescott** [danger/peril#364]
We are trying to host Peril internally on a variation of Cloud Foundry. Our setup requires for any external traffic to be done via a proxy service.

Looking for advice on how you would envision adding proxy support to Peril.

Looking around one way would be to add [this](https://www.npmjs.com/package/global-tunnel) global tunnel but I feel this is just a poor solution and would just be an ugly bolt on to your service.

Ultimately the details needed for proxy support are:

- host
- username
- password
- port

Currently Peril uses `ENV` for several config variables so I am wondering if Peril should look out for the details above and proxy if they are present.

If you agree on this approach could you point me into the right area I should be looking at within the Peril source?

**Comment by orta** [comment]
Sorry bud, I've got no idea - never needed to do it. At a guess you can use something [like this](https://github.com/TooTallNate/node-https-proxy-agent) and add that as an dependency to Peril's [fetch](https://github.com/danger/peril/blob/master/source/api/fetch.ts) function, and also into the [GitHub API[(https://github.com/octokit/rest.js#client-options) as the agent?

**Comment by Amri91** [comment]
You can try setting the environment variables `HTTP_PROXY` and `HTTPS_PROXY`, I have not tested this with peril.

**Comment by steprescott** [comment]
Ok, thanks. I'll try and put something together that works and submit it for your review.

**Comment by dapacheco** [comment]
I'll prefix this by stating that I'm not a JS / Node dev so it is likely that I've missed something, if so I apologise in advance.

Based on @orta hints I've looked into how the dependent libraries configure proxy support.
- https://github.com/octokit/rest.js uses `node-http-proxy-agent` to support proxies, it appears that proxy needs be passed as an option on initialisation: https://github.com/octokit/rest.js/blob/master/test/integration/agent-proxy/agent-proxy-test.js

- The `fetch` library also has the option to support proxies but this needs to be specified and it doesn't automatically make use of the `HTTP_PROXY` or `HTTPS_PROXY` env vars, this is highlighted in the following issue:
https://github.com/bitinn/node-fetch/issues/195

As such it appears that _out of the box_ HTTP proxies are not supported by the dependent libraries so some code changes are required. I'm going to try and make the relevant modifications but welcome the input of anyone with more platform experience 😄
