### ISSUE TITLE
How do third-party modules get added?

### ISSUE THREAD

**Issue by jlengstorf** [danger/peril#387]
Hey, team!

We're working on adding YAML validation to our Peril runs, and we're hitting an issue with third-party module includes. See https://github.com/gatsbyjs/gatsby/runs/22607335 for details.

Relevant error message:

```
Cannot find module 'joi'
VMError: Cannot find module 'joi'
    at _require (/app/node_modules/vm2/lib/sandbox.js:246:25)
    at Object.<anonymous> (/app/danger-0.v2sfufgp6wh.ts:5:13)
    at NodeVM.run (/app/node_modules/vm2/lib/main.js:427:27)
    at Object.<anonymous> (/app/node_modules/danger/distribution/runner/runners/vm2.js:100:37)
    at step (/app/node_modules/danger/distribution/runner/runners/vm2.js:43:23)
    at Object.next (/app/node_modules/danger/distribution/runner/runners/vm2.js:24:53)
    at /app/node_modules/danger/distribution/runner/runners/vm2.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/danger/distribution/runner/runners/vm2.js:14:12)
    at Object.exports.runDangerfileEnvironment (/app/node_modules/danger/distribution/runner/runners/vm2.js:83:121)
```

If I understand the lifecycle correctly, when we deploy to Heroku, the `postinstall` event should install all dependencies. Just to be sure, I ran this:

```
heroku run npm install -a gatsby-peril
```

And saw the logs I would expect (as well as a whole lot of errors that didn't crash the process, so I assume maybe those are expected?):

```
$ yarn run setup:plugins && yarn run setup:env
$ node out/scripts/setup-plugins.js
Installing: @slack/client, joi, js-yaml
```

These are identified in our [Peril settings](https://github.com/gatsbyjs/peril-gatsbyjs/blob/25e80023f2de848a591fbd1bb01ffddd5494d1dc/peril.settings.json#L3-L7) and implemented in [this rule](https://github.com/gatsbyjs/peril-gatsbyjs/blob/master/rules/validate-yaml.ts).

Are we missing something? Thanks!

**Comment by orta** [comment]
Nope - that should be everything I think `o.0`

**Comment by jlengstorf** [comment]
This was on me. I was restarting the app, but hadn't actually _built_ it. 🤦‍♂️

**Comment by orta** [comment]
Hah, I've been there for sure. That sucks. Can docs be improved somewhere?

**Comment by jlengstorf** [comment]
I don't think so. It's mostly me being unfamiliar with having a repo that we _don't_ edit on Heroku, and a repo that we _do_ edit that doesn't trigger rebuilds. Short of either a webhook setup to trigger Heroku rebuilds on repo changes or a rearchitecture to colocate the rules and a copy of Peril in the same app (e.g. install Peril as a dependency in the repo that implements rules and deploy _that_ to Heroku), I think it's just something I have to get used to remembering to do. 🤷‍♂️

**Comment by aequasi** [comment]
> Short of either a webhook setup to trigger Heroku rebuilds on repo changes 

This could be an easy win, not sure how complicated it might be though. 

Is there a suggested way to trigger a re-build?

**Comment by orta** [comment]
There [are hooks](https://github.com/danger/peril/blob/master/api/source/plugins/installationSettingsUpdater.ts) inside peril for determining that the json file has changed, so using the heroku API from that to trigger a re-build could be feasilbe?

**Comment by aequasi** [comment]
Could also run `yarn run setup` during `start`, that way a restart would be enough, instead of a full redeploy?

**Comment by orta** [comment]
Yeah, that would make it reboot slower, but I think that's an acceptable tradeoff
