### ISSUE TITLE
Allow for project_card events at organization level

### ISSUE THREAD

**Issue by flovilmart** [danger/peril#388]
We make a great use of GitHub projects at organization level, and we wanted to automate assigning the issue to the user moving the project card into an 'in progress' column.

At this moment, `project_card` emitted from organizations are swallowed and not run by peril.

They pose no particular issue to run `rules` hooks upon. (we run them with a fork of peril with success just by checking `event !== 'project_card'` [here](https://github.com/danger/peril/blob/master/source/github/events/github_runner.ts#L124))

What would it take to generalize this feature so projects can be handled easily?

**Comment by orta** [comment]
Good Q - I made that choice 2 years ago, I'm not sure it even still stands - I think Peril could probably handle it now natively. Could be worth just removing those checks and seeing if everything runs fine.

**Comment by flovilmart** [comment]
So far on the project_cards it’s all good. I’m not sure which subsystem requires the repository to be set. I’ll have a look in the coming days and let you know.

Any hunch as whether or not something could fall apart in the top of your head? The DSL May need an update as repository will definitely be optional

**Comment by flovilmart** [comment]
Alrighty then! I’ll keep an eye on it. We don’t plan (yet) to use another hook than this one. Would you like to see a Pr that opens it all up?

**Comment by orta** [comment]
This is in

**Comment by flovilmart** [comment]
Awesome! Haven’t seen anything bad happen yet
