### ISSUE TITLE
Question: Can I use Peril for my org for both internal & OSS contributors

### ISSUE THREAD

**Issue by brbrr** [danger/peril#398]
Hi! 

We are in https://github.com/Automattic using Danger for a bunch of repos, But now we are running into its limitations - one of the main limitations: Private Access token, which makes it not possible to use danger for OSS contributors (which are very valuable for us).

Will using Peril will help us resolve this problem? We want to make Danger be able to access our org private information (e.g. its members).

(Sorry for asking the question in repo)

**Comment by orta** [comment]
Yeah, Peril would fix that as it's a GitHub App with access to everything 👍

**Comment by brbrr** [comment]
Thanks!
