### ISSUE TITLE
"disable_github_check" setting not taking effect

### ISSUE THREAD

**Issue by jtreanor** [danger/peril#421]
Hi again 👋 

Peril has been working nicely for us for the past few days thanks to the workaround for https://github.com/danger/peril/issues/367.

I have encountered an issue today where the `disable_github_check` setting does not seem to be working. This morning I added this settings block to our peril settings:

```
"settings": {
  "disable_github_check": true
}
```

However, it isn't taking effect. I tried restarting Peril and even re-deploying to heroku but the Danger comments on PRs are still like `Danger run resulted in 1 fail and 1 warning; to find out more, see the checks page.` instead of commenting the issues directly on the PR.

Is there anything I can do to help diagnose this issue?

You can see the full settings file here: https://github.com/wordpress-mobile/peril-settings/blob/master/peril-settings.json.

Here is a PR with the failing comment: https://github.com/wordpress-mobile/WordPress-iOS/pull/11105#issuecomment-465965132

**Comment by orta** [comment]
Hrm, interesting, that setting works on the Artsy repo. Maybe that bool should just be flipped it to be the opposite way around TBH, I can't imagine anyone actually wanting that enabled.

**Comment by jtreanor** [comment]
Yeah, it is strange. I certainly agree that it would make sense for the default to be true but I'm curious why the settings changes aren't taking effect for me.

For what its worth, I have made many changes to `rules`/`repos`  and had them take effect as expected.

**Comment by jtreanor** [comment]
My settings are:

```
"settings": {
    "ignored_repos": ["wordpress-mobile/peril-settings"],
    "disable_github_check": true
}
```

I added this log line to https://github.com/danger/peril/blob/master/api/source/danger/danger_runner.ts#L139:

```
console.log(options);
``` 

On each PR run, it prints:

```
{ env_vars: [],
ignored_repos: [ 'wordpress-mobile/peril-settings' ],
modules: [] }
```

So something is causing the `disable_github_check` setting to be be passed through to here 🤔

**Comment by orta** [comment]
Got it:

https://github.com/danger/peril/blob/master/api/source/db/json.ts#L87-L111

This will need the setting added

**Comment by jtreanor** [comment]
Great! I can make a PR for that.

**Comment by orta** [comment]
Nice, yeah, I'm still deep into #417 - I'd recommend making that on your branch, (or look at #419 if you're feeling ) and we can cherry pick it into master too

**Comment by jtreanor** [comment]
Thanks, @orta!

Of course, I won't be able to use this right away because of https://github.com/danger/peril/issues/419 but I will try to make time to look at that next week.
