### ISSUE TITLE
relative imports on heroku

### ISSUE THREAD

**Issue by roopakv** [danger/peril#460]
Does anyone know why we dont have relative import support on heroku? Would love to help fix this.

**Comment by aequasi** [comment]
And whether or not there is a workaround?

**Comment by orta** [comment]
I'm afraid you'll have to read the code, off the top of my head. I can't think of a reason why it'd be limited to just the multi-user mode

**Comment by aequasi** [comment]
For some more context: This supposedly should work with [this pr](https://github.com/danger/peril/pull/346), but when using typescript, I'm not able to get them (with import and require)

**Comment by aequasi** [comment]
Where exactly is the code that does the github api replacement?

**Comment by aequasi** [comment]
Does the danger version matter at all? Artsy devs against [^7](https://github.com/artsy/peril-settings/blob/master/package.json#L26), but latest is ^9

**Comment by orta** [comment]
That PR indicated that the problem was in how code is evaluated by Danger (in Peril), so I doubt the danger version will affect it.

I think that constraint might have changed since then. You should try removing the check and see if it works without that 👍

**Comment by aequasi** [comment]
It does not. Kinda out of my depth at this point. The peril stack is pretty big 😄
