### ISSUE TITLE
[Bug] Initial Setup Clarification

### ISSUE THREAD

**Issue by samdmarshall** [danger/peril#63]
When following the instructions in the readme file for performing initial setup and installation, I came across the following errors:

* `PERIL_BOT_USER_ID` marked as not required, but presented a hard-error when running `yarn start` without it defined.
* `WEB_URL` marked as not used, but presented a hard-error when running `yarn start` without it defined.
* `PAPERTRAIL_URL`/`PAPERTRAIL_PORT` marked as optional, but presented a hard-error when running `yarn start` without them defined.
* Upon running `yarn start`, got two warning messages printed to the console:
  ```
  WARNING: No configurations found in configuration directory:/Users/Samantha/Projects/peril/config
  WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
  ```
* Once the server was running and forwarded by `ngrok`, resending the initial creation message from the integration was picked up correctly and forwarded by `ngrok`, however didn't cause `peril` to progress in state to setup the new installation.

**Comment by orta** [comment]
re the last one - Danger should be looking for something like:

<img width="566" alt="screen shot 2017-04-23 at 10 56 12" src="https://cloud.githubusercontent.com/assets/49038/25314514/81e76ea4-2813-11e7-9055-6e2471fc5488.png">

**Comment by orta** [comment]
I wonder if there's a difference between installing on all repos vs one repo, maybe that could be it?

**Comment by samdmarshall** [comment]
There might be something that needs to be done on the GitHub side to make understanding the setup with integrations more understandable, since most of my confusion comes from their interface, and not peril's.

**Comment by orta** [comment]
Calling this closed for now 👍

**Comment by orta** [comment]
Mainly as I think I've addressed a chunk of this
